### PR TITLE
*: upgrade to go-ipfs v0.13.0 and Go 1.18

### PR DESCRIPTION
**Pull request by mrd0ll4r**
This upgrades IPFS to v0.13.0. This also allows us to use Go1.18, which is nice, because 1.16 is deprecated :)

### CODE REVIEW

**Comment by lgehr** [comment]
I can not review 'cause I have no write access

**Comment by lgehr** [comment]
Also could we not ditch the docker file and just build locally?

**Comment by mrd0ll4r** [comment]
No, I want to keep the dockerfile. I recommend everyone to use it, since building manually is such a giant pain. And as such, we'll use it ourselves and test it in CI :)

**Review by lgehr — APPROVED** [review]
LGTM

**Comment by lgehr** [comment]
My review is worthless in the eyes of github :/

**Comment by mrd0ll4r** [comment]
Not anymore! :)

**Pull request merged**
